version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1

    working_directory: ~/repo

    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       - v1-dependencies-

      - run:
          name: Install packages
          command: npm install

      - run:
          name: Build project
          command: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - src

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm run test

  deploy:
    docker:
      - image: circleci/node:12.9.1

    steps:
      - attach_workspace:
          at: ~/repo

      - add_ssh_keys:
          fingerprints:
            - "5b:9e:e9:f9:77:f3:a3:0e:49:88:d9:7f:62:ff:4d:bc"

      - run:
          name: deploy to hosting
          command: |
            ssh ${DEPLOY_USER}@${DEPLOY_SERVER} -o StrictHostKeyChecking=no
            exit
            scp -r -o StrictHostKeyChecking=no ~/dist ${DEPLOY_USER}@${DEPLOY_SERVER}:${DEPLOY_DIR}

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
