on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Semantic release
              uses: cycjimmy/semantic-release-action@v3
              id: semantic
              with:
                  extra_plugins: |
                      @semantic-release/git
                      @semantic-release/changelog
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
